for (let i=1; i <=100; ++i){
    // document.writeln(i);
    console.log(i);
    var ciao = `sono ciao e sono uguale a :` + i;
}

console.log(ciao);

// SOPRA ERA L'ESEMPIO SVOLTO IN CLASSE, L'HO RISCRITTO PER MEMORIZZARLO BENE


// - PER CAPIRE SE UN NUMERO E' DIVISIBILE PER UN ALTRO POSSO UTILIZZARE IL SIMBOLO DELLA PERCENTUALE CON I 3 NUMERI IN QUESTIONE, QUINDI 3,5,15, SE AVRO RESTO 0 NEL CASO DEL 3 ALLORA SIGNIFICA CHE IL NUMERO E' DIVISIBILE PER 3 ALLORA FACCIO SCRIVERE BUZZ. STESSO DISCORSO PER 5 E 15 CON FIZZ E FIZZBUZZ.

